name: Update Assets
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
jobs:
  build-for-course-in-school:
    name: Assets of course-in-school
    runs-on: ubuntu-latest
    env:
      leave_date: "2021-06-23"
      time_zone_diff: 8
      target_leave_days_badge: assets/course-in-school/leave_days_badge.svg
      target_last_modify_time_badge: assets/course-in-school/last_modify_time_badge.svg
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Image Assets
        run: |
          date_start=${{env.leave_date}}
          time_zone_diff=${{env.time_zone_diff}}
          last_modify_time_badge_content=`date -d "$time_zone_diff hours" +"%Y--%m--%d_%H:%M:%S"`
          date_end=`date -d "$time_zone_diff hours" +"%Y-%m-%d"`
          date_start_second=`date -d"$date_start" +"%s"`
          date_end_second=`date -d"$date_end" +"%s"`
          interval=$[$date_end_second-$date_start_second]
          interval_days=$[$interval/86400]
          mkdir -p `dirname ${{env.target_leave_days_badge}}`
          wget "https://img.shields.io/badge/leave-${interval_days}_days-green.svg?style=for-the-badge" -O ${{env.target_leave_days_badge}}
          mkdir -p `dirname ${{env.target_last_modify_time_badge}}`
          wget "https://img.shields.io/badge/last_modify-${last_modify_time_badge_content}-orange.svg?style=for-the-badge" -O ${{env.target_last_modify_time_badge}}
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: Update Assets
          pull: '--rebase'
          default_author: user_info
  build-for-Ohto-Ai:
    name: Assets of Ohto-Ai
    runs-on: ubuntu-latest
    strategy:
      matrix:
        owner: [ohto-ai, beiklive, zhouhuan666, Aakjaeryoung, XSSaGY]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ matrix.owner }}
          gif_out_path: assets/${{ matrix.owner }}/github-contribution-grid-snake.gif
          svg_out_path: assets/${{ matrix.owner }}/github-contribution-grid-snake.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: Update Assets
          pull: '--rebase'
          default_author: user_info
