name: Update Assets
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      target_leave_days_badge: assets/course-in-school/leave_days_badge.svg
      target_last_modify_time_badge: assets/course-in-school/last_modify_time_badge.svg
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate Image Assets
        run: |
          date_start=${{secrets.LEAVE_DATE}}
          time_zone_diff=${{secrets.TIME_ZONE_DIFF}}
          last_modify_time_badge_content=`date -d "$time_zone_diff hours" +"%Y--%m--%d_%H:%M:%S"`
          date_end=`date -d "$time_zone_diff hours" +"%Y-%m-%d"`
          date_start_second=`date -d"$date_start" +"%s"`
          date_end_second=`date -d"$date_end" +"%s"`
          interval=$[$date_end_second-$date_start_second]
          interval_days=$[$interval/86400]
          mkdir -p `dirname ${{target_leave_days_badge}}`
          wget "https://img.shields.io/badge/leave-${interval_days}_days-green.svg?style=for-the-badge" -O ${{target_leave_days_badge}}
          mkdir -p `dirname ${{target_last_modify_time_badge}}`
          wget "https://img.shields.io/badge/last_modify-${last_modify_time_badge_content}-orange.svg?style=for-the-badge" -O ${{target_last_modify_time_badge}}
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: assets/github-contribution-grid-snake.gif
          svg_out_path: assets/github-contribution-grid-snake.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: "Update Assets"
          default_author: user_infoname: Update Assets
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      target_leave_days_badge: assets/course-in-school/leave_days_badge.svg
      target_last_modify_time_badge: assets/course-in-school/last_modify_time_badge.svg
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate Image Assets
        run: |
          date_start=${{secrets.LEAVE_DATE}}
          time_zone_diff=${{secrets.TIME_ZONE_DIFF}}
          last_modify_time_badge_content=`date -d "$time_zone_diff hours" +"%Y--%m--%d_%H:%M:%S"`
          date_end=`date -d "$time_zone_diff hours" +"%Y-%m-%d"`
          date_start_second=`date -d"$date_start" +"%s"`
          date_end_second=`date -d"$date_end" +"%s"`
          interval=$[$date_end_second-$date_start_second]
          interval_days=$[$interval/86400]
          mkdir -p `dirname ${{target_leave_days_badge}}`
          wget "https://img.shields.io/badge/leave-${interval_days}_days-green.svg?style=for-the-badge" -O ${{target_leave_days_badge}}
          mkdir -p `dirname ${{target_last_modify_time_badge}}`
          wget "https://img.shields.io/badge/last_modify-${last_modify_time_badge_content}-orange.svg?style=for-the-badge" -O ${{target_last_modify_time_badge}}
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: assets/github-contribution-grid-snake.gif
          svg_out_path: assets/github-contribution-grid-snake.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: "Update Assets"
          default_author: user_info
